config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout' }
  resources :portfolios

  get 'java-items', to: 'portfolios#java'
  
  namespace :admin do
    get 'dashboard/main'
    get 'dashboard/user'
    get 'dashboard/blog'
  end
  
  get 'about', to: 'pages#about'
  get 'contact', to:'pages#contact', as:'call'
  resources :blogs
  resources :posts

  get 'posts/*missing', to:'posts#missing'

  get 'query/:something', to:'pages#something'

  root to:'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                   reject_if: lambda { |attr| attr['name'].blank? }               
    include Placeholder
    validates_presence_of :title, :sub_title, :body, :thamb_img, :main_img

    # Below both methods work same 1. Normal, 2. Lambda (Encapsulating entire process in ruby)
    # 1.
    def self.java
        where(sub_title: 'Java')
    end
    # 2.
    def self.selenium
        where(sub_title: 'Selenium WebDriver')
    end

    #implementing the custome scope video 78
    scope :ruby_on_rails, -> { where(sub_title: 'Ruby on Rails') }

    
    #setting default values if nill or not found
    after_initialize :set_defaults
    def set_defaults
        #type 1
        if self.thamb_img == nil
         self.thamb_img = 'https://via.placeholder.com/300x150'
        end
        #type 2 (Short Cut method)
        self.main_img ||= Placeholder.image_generator(height:'700', width:'300')
        #'https://via.placeholder.com/700x300'
    end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    layout "portfolio"
    
    def index 
        @portfolio_items = Portfolio.selenium
    end

    # VIEW file created for the java defination
    def java
        @java_portfolio_items = Portfolio.java
    end

    def new
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)

        respond_to do |format|
            if @portfolio_item.save
                format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
                format.json { render :portfolios, status: :created, location: @portfolio_item }
            else
                format.html { render :new }
                format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @portfolio_item = Portfolio.find(params[:id])
    end

    def update
        @portfolio_item = Portfolio.find(params[:id])
        respond_to do |format|
            if @portfolio_item.update(portfolio_params)
                format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
                format.json { render :show, status: :ok, location: @portfolio_item }
            else
                format.html { render :edit }
                format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
            end
        end
    end

    def show
        @portfolio_item = Portfolio.find(params[:id])
    end

    def destroy
        @portfolio_item = Portfolio.find(params[:id])
        @portfolio_item.destroy
        respond_to do |format|
            format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully Deleted.' }
            format.json { head :no_content }
        end
    end

    private
    def portfolio_params
        params.require(:portfolio).permit(:title, 
                                          :sub_title, 
                                          :body, 
                                          technologies_attributes: [:name]
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :sub_title %>
    <%= f.text_field :sub_title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <p>Technologies</p>
  <div class="field">
  <ul>
    <%= f.fields_for :technologies do |tech| %>
    <li>
      <%= tech.label :name %>
      <%= tech.text_field :name %>
    </li>
    <% end %>
  </ul>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<hr>
<p><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></p>
<p><%= portfolio_item.sub_title %></p>
<p><%= portfolio_item.body %></p>
<p><%= image_tag portfolio_item.thamb_img if !portfolio_item.thamb_img.nil? %></p>
<td><%= link_to 'Show', portfolio_item %></td>
<td><%= link_to 'Edit', edit_portfolio_path(portfolio_item) %></td>
<td><%= link_to 'Delete', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>  

app/views/portfolios/edit.html.erb
<h1> Edit the Portfolio Item </h1>

 <%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1> Portfolio items </h1>

<%= link_to 'Create new item', new_portfolio_path %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/java.html.erb
<h1> Java Portfolio items </h1>

<%= link_to 'Create new item', new_portfolio_path %>
<% @java_portfolio_items.each do |portfolio_item| %>
    <hr>
    <p><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></p>
    <p><%= portfolio_item.sub_title %></p>
    <p><%= portfolio_item.body %></p>
    <p><%= image_tag portfolio_item.thamb_img if !portfolio_item.thamb_img.nil? %></p>
    <td><%= link_to 'Show', portfolio_item %></td>
    <td><%= link_to 'Edit', edit_portfolio_path(portfolio_item) %></td>
    <td><%= link_to 'Delete', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
<% end %>

app/views/portfolios/new.html.erb
  <h1> Create Portfolio Item </h1>

  <%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @portfolio_item.thamb_img %>
<p>
  <strong>Title </strong>
  <%= @portfolio_item.title %>
</p>

<p>
  <strong>Sub Title:</strong>
  <%= @portfolio_item.sub_title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @portfolio_item.body %>
</p>

<p><strong>Technologies:</strong></p>

<%= @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>

<%= link_to 'Edit', edit_portfolio_path(@portfolio_item) %> |
<%= link_to 'Back', portfolios_path %>